# Generated by Django 6.0.3 on 2026-04-05 11:13

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulatedPersona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Stable identifier for prompt/runtime lookup inside the simulated tenant.', max_length=120)),
                ('full_name', models.CharField(max_length=255)),
                ('first_name', models.CharField(blank=True, max_length=120)),
                ('last_name', models.CharField(blank=True, max_length=120)),
                ('job_title', models.CharField(blank=True, max_length=255)),
                ('simulated_company_name', models.CharField(blank=True, max_length=255)),
                ('seniority', models.CharField(choices=[('intern', 'Intern'), ('junior', 'Junior'), ('mid', 'Mid'), ('senior', 'Senior'), ('lead', 'Lead'), ('director', 'Director'), ('vp', 'VP'), ('c_level', 'C-Level'), ('owner', 'Owner')], default='mid', max_length=32)),
                ('notes', models.TextField(blank=True)),
                ('character_seed', models.TextField(blank=True, help_text='Internal short seed describing the persona core.')),
                ('formality', models.DecimalField(decimal_places=2, default=Decimal('0.50'), max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('1.00'))])),
                ('patience', models.DecimalField(decimal_places=2, default=Decimal('0.50'), max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('1.00'))])),
                ('risk_tolerance', models.DecimalField(decimal_places=2, default=Decimal('0.50'), max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('1.00'))])),
                ('change_openness', models.DecimalField(decimal_places=2, default=Decimal('0.50'), max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('1.00'))])),
                ('cooperation', models.DecimalField(decimal_places=2, default=Decimal('0.50'), max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('1.00'))])),
                ('resistance', models.DecimalField(decimal_places=2, default=Decimal('0.50'), max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('1.00'))])),
                ('responsiveness', models.DecimalField(decimal_places=2, default=Decimal('0.50'), max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('1.00'))])),
                ('detail_orientation', models.DecimalField(decimal_places=2, default=Decimal('0.50'), max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('1.00'))])),
                ('communication_style', models.CharField(choices=[('concise', 'Concise'), ('balanced', 'Balanced'), ('explanatory', 'Explanatory'), ('relational', 'Relational'), ('direct', 'Direct')], default='balanced', max_length=32)),
                ('preferred_language', models.CharField(default='en', max_length=32)),
                ('typical_reply_latency_hours', models.PositiveIntegerField(default=24)),
                ('goals', models.JSONField(blank=True, default=list)),
                ('pains', models.JSONField(blank=True, default=list)),
                ('priorities', models.JSONField(blank=True, default=list)),
                ('internal_pressures', models.JSONField(blank=True, default=list)),
                ('budget_context', models.TextField(blank=True)),
                ('decision_frame', models.CharField(choices=[('individual', 'Individual'), ('manager_review', 'Manager Review'), ('committee', 'Committee'), ('procurement', 'Procurement'), ('exec_sponsor', 'Executive Sponsor'), ('unknown', 'Unknown')], default='unknown', max_length=32)),
                ('decision_criteria', models.JSONField(blank=True, default=list)),
                ('blockers', models.JSONField(blank=True, default=list)),
                ('interest_level', models.DecimalField(decimal_places=2, default=Decimal('0.30'), max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('1.00'))])),
                ('trust_level', models.DecimalField(decimal_places=2, default=Decimal('0.30'), max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('1.00'))])),
                ('saturation_level', models.DecimalField(decimal_places=2, default=Decimal('0.10'), max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('1.00'))])),
                ('urgency_level', models.DecimalField(decimal_places=2, default=Decimal('0.20'), max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('1.00'))])),
                ('frustration_level', models.DecimalField(decimal_places=2, default=Decimal('0.10'), max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('1.00'))])),
                ('relational_temperature', models.CharField(choices=[('cold', 'Cold'), ('guarded', 'Guarded'), ('neutral', 'Neutral'), ('warm', 'Warm'), ('engaged', 'Engaged'), ('friction', 'Friction')], default='neutral', max_length=32)),
                ('last_interaction_at', models.DateTimeField(blank=True, null=True)),
                ('state_last_updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mailbox_account', models.ForeignKey(blank=True, help_text='Mailbox actor primarily associated with this simulated persona.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='simulated_personas', to='tenancy.mailboxaccount')),
                ('operating_organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulated_personas', to='tenancy.operatingorganization')),
            ],
            options={
                'ordering': ['full_name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SimulatedPersonaMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('general', 'General'), ('relation', 'Relation'), ('sales', 'Sales'), ('objection', 'Objection'), ('internal', 'Internal')], default='general', max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('salience', models.DecimalField(decimal_places=2, default=Decimal('0.50'), max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('1.00'))])),
                ('source', models.CharField(default='manual', max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memories', to='simulated_personas.simulatedpersona')),
            ],
            options={
                'ordering': ['-salience', '-updated_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='simulatedpersona',
            index=models.Index(fields=['operating_organization', 'is_active'], name='simulated_p_operati_be4ec5_idx'),
        ),
        migrations.AddIndex(
            model_name='simulatedpersona',
            index=models.Index(fields=['operating_organization', 'mailbox_account'], name='simulated_p_operati_258cb0_idx'),
        ),
        migrations.AddIndex(
            model_name='simulatedpersona',
            index=models.Index(fields=['operating_organization', 'slug'], name='simulated_p_operati_9d81b0_idx'),
        ),
        migrations.AddIndex(
            model_name='simulatedpersona',
            index=models.Index(fields=['relational_temperature', 'is_active'], name='simulated_p_relatio_ba38e7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='simulatedpersona',
            unique_together={('operating_organization', 'slug')},
        ),
        migrations.AddIndex(
            model_name='simulatedpersonamemory',
            index=models.Index(fields=['persona', 'kind', 'is_active'], name='simulated_p_persona_dc76c1_idx'),
        ),
        migrations.AddIndex(
            model_name='simulatedpersonamemory',
            index=models.Index(fields=['persona', 'salience'], name='simulated_p_persona_e72a3c_idx'),
        ),
    ]
