# Generated by Django 6.0.3 on 2026-03-29 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulated_personas', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='simulatedpersona',
            new_name='simulated_p_operati_be4ec5_idx',
            old_name='sim_persona_org_active_idx',
        ),
        migrations.RenameIndex(
            model_name='simulatedpersona',
            new_name='simulated_p_operati_258cb0_idx',
            old_name='sim_persona_org_mailbox_idx',
        ),
        migrations.RenameIndex(
            model_name='simulatedpersona',
            new_name='simulated_p_operati_9d81b0_idx',
            old_name='sim_persona_org_slug_idx',
        ),
        migrations.RenameIndex(
            model_name='simulatedpersona',
            new_name='simulated_p_relatio_ba38e7_idx',
            old_name='sim_persona_temp_active_idx',
        ),
        migrations.RenameIndex(
            model_name='simulatedpersonamemory',
            new_name='simulated_p_persona_dc76c1_idx',
            old_name='sim_memory_persona_kind_idx',
        ),
        migrations.RenameIndex(
            model_name='simulatedpersonamemory',
            new_name='simulated_p_persona_e72a3c_idx',
            old_name='sim_memory_persona_salience_idx',
        ),
    ]
