# Generated by Django 6.0.3 on 2026-03-31 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inferences', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inferencerecord',
            name='inference_value',
        ),
        migrations.RemoveField(
            model_name='inferencerecord',
            name='rationale',
        ),
        migrations.AddField(
            model_name='inferencerecord',
            name='payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='inferencerecord',
            name='confidence',
            field=models.FloatField(default=0.5),
        ),
        migrations.AlterField(
            model_name='inferencerecord',
            name='source_id',
            field=models.IntegerField(),
        ),
    ]
