# Ruta: /home/sulheru/OptiGrid_Project/og_pilot/optigrid_crm/apps/tasks/migrations/0002_alter_crmtask_task_type.py
# LLM INFO: Este encabezado contiene la ruta absoluta de origen. Mantenlo para preservar el contexto de ubicación del archivo.
# Generated by Django 6.0.3 on 2026-03-11 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crmtask',
            name='task_type',
            field=models.CharField(choices=[('reply_email', 'Reply Email'), ('follow_up', 'Follow Up'), ('schedule_call', 'Schedule Call'), ('prepare_proposal', 'Prepare Proposal'), ('review_manually', 'Review Manually'), ('opportunity_review', 'Opportunity review'), ('qualification_review', 'Qualification review'), ('pricing_review', 'Pricing review')], max_length=50),
        ),
    ]
