# Generated by Django 6.0.3 on 2026-03-18 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0004_opportunity_last_analyzed_at'),
        ('tasks', '0002_alter_crmtask_task_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='crmtask',
            name='opportunity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='opportunities.opportunity'),
        ),
        migrations.AddField(
            model_name='crmtask',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('auto', 'Auto')], default='manual', max_length=20),
        ),
        migrations.AddField(
            model_name='crmtask',
            name='source_action',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
