# Ruta: /home/sulheru/OptiGrid_Project/og_pilot/optigrid_crm/apps/opportunities/migrations/0003_opportunity_source_recommendation.py
# LLM INFO: Este encabezado contiene la ruta absoluta de origen. Mantenlo para preservar el contexto de ubicación del archivo.
# Generated by Django 6.0.3 on 2026-03-12 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0002_initial'),
        ('recommendations', '0002_alter_airecommendation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='source_recommendation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spawned_opportunities', to='recommendations.airecommendation'),
        ),
    ]
