# Ruta: /home/sulheru/OptiGrid_Project/og_pilot/optigrid_crm/apps/contacts/migrations/0001_initial.py
# Generated by Django 6.0.3 on 2026-03-08 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('job_title', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('email_status', models.CharField(default='not_found', max_length=50)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('contact_status', models.CharField(default='identified', max_length=50)),
                ('confidence', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='companies.company')),
            ],
        ),
    ]
