# Generated by Django 6.0.3 on 2026-04-05 11:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Identity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled'), ('archived', 'Archived')], default='active', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Identity',
                'verbose_name_plural': 'Identities',
                'ordering': ['email'],
            },
        ),
        migrations.CreateModel(
            name='OperatingOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('legal_name', models.CharField(blank=True, max_length=255)),
                ('primary_domain', models.CharField(blank=True, max_length=255)),
                ('is_simulated', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('provisional', 'Provisional'), ('active', 'Active'), ('paused', 'Paused'), ('archived', 'Archived')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_operating_organizations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Operating Organization',
                'verbose_name_plural': 'Operating Organizations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MailboxAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('account_key', models.CharField(max_length=120)),
                ('provider', models.CharField(default='mail_stub', max_length=100)),
                ('is_primary', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled'), ('archived', 'Archived')], default='active', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mailbox_accounts', to=settings.AUTH_USER_MODEL)),
                ('operating_organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mailbox_accounts', to='tenancy.operatingorganization')),
            ],
            options={
                'verbose_name': 'Mailbox Account',
                'verbose_name_plural': 'Mailbox Accounts',
                'ordering': ['operating_organization__name', 'email'],
            },
        ),
        migrations.CreateModel(
            name='EmailIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=200)),
                ('account_key', models.CharField(max_length=120, unique=True)),
                ('provider', models.CharField(default='system', max_length=100)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_public_domain', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled'), ('archived', 'Archived')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operating_organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_identities', to='tenancy.operatingorganization')),
            ],
            options={
                'ordering': ['email'],
            },
        ),
        migrations.CreateModel(
            name='CorporateMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('member', 'Member')], default='member', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('invited', 'Invited'), ('disabled', 'Disabled'), ('archived', 'Archived')], default='active', max_length=20)),
                ('is_default', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('identity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='tenancy.identity')),
                ('operating_organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='tenancy.operatingorganization')),
            ],
            options={
                'verbose_name': 'Corporate Membership',
                'verbose_name_plural': 'Corporate Memberships',
                'ordering': ['operating_organization__name', 'identity__email'],
            },
        ),
        migrations.CreateModel(
            name='CorporateDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255, unique=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operating_organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corporate_domains', to='tenancy.operatingorganization')),
            ],
            options={
                'verbose_name': 'Corporate Domain',
                'verbose_name_plural': 'Corporate Domains',
                'ordering': ['domain'],
            },
        ),
        migrations.CreateModel(
            name='PublicEmailDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['domain'],
                'indexes': [models.Index(fields=['domain'], name='tenancy_pub_domain_6ac9ce_idx'), models.Index(fields=['is_active'], name='tenancy_pub_is_acti_4864a2_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='operatingorganization',
            index=models.Index(fields=['slug'], name='tenancy_ope_slug_8c3e03_idx'),
        ),
        migrations.AddIndex(
            model_name='operatingorganization',
            index=models.Index(fields=['primary_domain'], name='tenancy_ope_primary_29246f_idx'),
        ),
        migrations.AddIndex(
            model_name='operatingorganization',
            index=models.Index(fields=['status'], name='tenancy_ope_status_1a02a2_idx'),
        ),
        migrations.AddConstraint(
            model_name='mailboxaccount',
            constraint=models.UniqueConstraint(fields=('operating_organization', 'email'), name='uniq_mailbox_org_email'),
        ),
        migrations.AddConstraint(
            model_name='mailboxaccount',
            constraint=models.UniqueConstraint(fields=('operating_organization', 'account_key'), name='uniq_mailbox_org_key'),
        ),
        migrations.AddIndex(
            model_name='emailidentity',
            index=models.Index(fields=['email'], name='tenancy_ema_email_25df0b_idx'),
        ),
        migrations.AddIndex(
            model_name='emailidentity',
            index=models.Index(fields=['operating_organization', 'status'], name='tenancy_ema_operati_5f816f_idx'),
        ),
        migrations.AddIndex(
            model_name='corporatemembership',
            index=models.Index(fields=['operating_organization', 'status'], name='cm_org_st_idx'),
        ),
        migrations.AddIndex(
            model_name='corporatemembership',
            index=models.Index(fields=['identity', 'status'], name='cm_id_st_idx'),
        ),
        migrations.AddConstraint(
            model_name='corporatemembership',
            constraint=models.UniqueConstraint(fields=('identity', 'operating_organization'), name='uniq_id_org'),
        ),
        migrations.AddConstraint(
            model_name='corporatemembership',
            constraint=models.CheckConstraint(condition=models.Q(('role__in', ['owner', 'admin', 'member'])), name='corporate_membership_role_valid'),
        ),
        migrations.AddIndex(
            model_name='corporatedomain',
            index=models.Index(fields=['domain'], name='cd_dom_idx'),
        ),
        migrations.AddIndex(
            model_name='corporatedomain',
            index=models.Index(fields=['operating_organization', 'is_active'], name='cd_org_act_idx'),
        ),
    ]
