# Generated by Django 6.0.3 on 2026-03-31 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0003_identity_and_corporate_domains'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='corporatedomain',
            options={'ordering': ['domain'], 'verbose_name': 'Corporate Domain', 'verbose_name_plural': 'Corporate Domains'},
        ),
        migrations.AlterModelOptions(
            name='corporatemembership',
            options={'ordering': ['operating_organization__name', 'identity__email'], 'verbose_name': 'Corporate Membership', 'verbose_name_plural': 'Corporate Memberships'},
        ),
        migrations.AlterModelOptions(
            name='identity',
            options={'ordering': ['email'], 'verbose_name': 'Identity', 'verbose_name_plural': 'Identities'},
        ),
        migrations.AlterField(
            model_name='corporatemembership',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='corporatemembership',
            name='identity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='tenancy.identity'),
        ),
        migrations.AlterField(
            model_name='corporatemembership',
            name='operating_organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='tenancy.operatingorganization'),
        ),
        migrations.AlterField(
            model_name='corporatemembership',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('member', 'Member')], default='member', max_length=20),
        ),
        migrations.AlterField(
            model_name='corporatemembership',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('invited', 'Invited'), ('disabled', 'Disabled'), ('archived', 'Archived')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='identity',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='identity',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled'), ('archived', 'Archived')], default='active', max_length=20),
        ),
    ]
