# Generated by Django 6.0.3 on 2026-04-05 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CRMUpdateProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(max_length=50)),
                ('source_id', models.CharField(max_length=50)),
                ('proposal_type', models.CharField(max_length=100)),
                ('payload', models.JSONField(default=dict)),
                ('status', models.CharField(default='proposed', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RuleEvaluationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(max_length=50)),
                ('source_id', models.CharField(max_length=50)),
                ('trace', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
