# Generated by Django 6.0.3 on 2026-03-08 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CRMUpdateProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_entity_type', models.CharField(max_length=50)),
                ('target_entity_id', models.CharField(max_length=100)),
                ('proposed_change_type', models.CharField(max_length=100)),
                ('proposed_payload', models.JSONField()),
                ('confidence', models.FloatField()),
                ('approval_required', models.BooleanField(default=True)),
                ('proposal_status', models.CharField(default='proposed', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
