# Generated by Django 6.0.3 on 2026-03-31 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0002_remove_crmupdateproposal_approval_required_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RuleEvaluationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(max_length=50)),
                ('source_id', models.CharField(max_length=50)),
                ('trace', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='crmupdateproposal',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='crmupdateproposal',
            name='payload',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='crmupdateproposal',
            name='source_id',
            field=models.CharField(max_length=50),
        ),
    ]
