# Generated by Django 6.0.3 on 2026-04-05 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InboundDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('advance_opportunity', 'Advance opportunity'), ('send_information', 'Send information'), ('schedule_followup', 'Schedule follow-up'), ('mark_lost', 'Mark lost'), ('send_clarification', 'Send clarification')], max_length=32)),
                ('status', models.CharField(choices=[('suggested', 'Suggested'), ('applied', 'Applied'), ('dismissed', 'Dismissed')], default='suggested', max_length=16)),
                ('summary', models.CharField(blank=True, default='', max_length=255)),
                ('payload_json', models.JSONField(blank=True, default=dict)),
                ('requires_approval', models.BooleanField(default=True)),
                ('score', models.FloatField(default=0.0)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('risk_flags', models.JSONField(blank=True, default=list)),
                ('applied_automatically', models.BooleanField(default=False)),
                ('automation_reason', models.CharField(blank=True, default='', max_length=255)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InboundInterpretation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intent', models.CharField(choices=[('interested', 'Interested'), ('objection', 'Objection / Needs info'), ('delay', 'Delay / Not now'), ('rejection', 'Rejection'), ('unclear', 'Unclear')], default='unclear', max_length=32)),
                ('urgency', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=16)),
                ('sentiment', models.CharField(choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative')], default='neutral', max_length=16)),
                ('recommended_action', models.CharField(choices=[('advance_opportunity', 'Advance opportunity'), ('send_information', 'Send information'), ('schedule_followup', 'Schedule follow-up'), ('mark_lost', 'Mark lost'), ('send_clarification', 'Send clarification')], default='send_clarification', max_length=32)),
                ('confidence', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('rationale', models.TextField(blank=True, default='')),
                ('signals_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OutboundEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_type', models.CharField(choices=[('first_contact', 'First contact'), ('followup', 'Follow-up')], default='first_contact', max_length=30)),
                ('to_email', models.CharField(blank=True, default='', max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('sent', 'Sent'), ('failed', 'Failed')], default='draft', max_length=20)),
                ('generated_by', models.CharField(default='ai', max_length=50)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InboundEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_email', models.CharField(blank=True, default='', max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewed', 'Reviewed'), ('linked', 'Linked')], default='new', max_length=20)),
                ('reply_type', models.CharField(choices=[('interested', 'Interested'), ('not_now', 'Not now'), ('not_interested', 'Not interested'), ('needs_info', 'Needs info'), ('unclear', 'Unclear')], default='unclear', max_length=30)),
                ('received_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mailbox_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbound_emails', to='tenancy.mailboxaccount')),
                ('operating_organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbound_emails', to='tenancy.operatingorganization')),
            ],
            options={
                'ordering': ['-received_at', '-created_at'],
            },
        ),
    ]
