# Ruta: /home/sulheru/OptiGrid_Project/og_pilot/optigrid_crm/apps/emailing/migrations/0002_remove_emailthread_linked_company_and_more.py
# Generated by Django 6.0.3 on 2026-03-19 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailing', '0001_initial'),
        ('opportunities', '0004_opportunity_last_analyzed_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailthread',
            name='linked_company',
        ),
        migrations.RemoveField(
            model_name='emailthread',
            name='linked_contact',
        ),
        migrations.CreateModel(
            name='OutboundEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_email', models.CharField(blank=True, max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('sent', 'Sent'), ('failed', 'Failed')], default='draft', max_length=20)),
                ('generated_by', models.CharField(default='ai', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbound_emails', to='opportunities.opportunity')),
            ],
        ),
        migrations.DeleteModel(
            name='EmailMessage',
        ),
        migrations.DeleteModel(
            name='EmailThread',
        ),
    ]
