# Generated by Django 6.0.3 on 2026-04-05 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('emailing', '0001_initial'),
        ('opportunities', '0001_initial'),
        ('recommendations', '0001_initial'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inboundemail',
            name='opportunity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbound_emails', to='opportunities.opportunity'),
        ),
        migrations.AddField(
            model_name='inbounddecision',
            name='inbound_email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_decisions', to='emailing.inboundemail'),
        ),
        migrations.AddField(
            model_name='inboundinterpretation',
            name='inbound_email',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_interpretation', to='emailing.inboundemail'),
        ),
        migrations.AddField(
            model_name='inbounddecision',
            name='interpretation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='emailing.inboundinterpretation'),
        ),
        migrations.AddField(
            model_name='outboundemail',
            name='mailbox_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outbound_emails', to='tenancy.mailboxaccount'),
        ),
        migrations.AddField(
            model_name='outboundemail',
            name='operating_organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outbound_emails', to='tenancy.operatingorganization'),
        ),
        migrations.AddField(
            model_name='outboundemail',
            name='opportunity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbound_emails', to='opportunities.opportunity'),
        ),
        migrations.AddField(
            model_name='outboundemail',
            name='source_inbound',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_followups', to='emailing.inboundemail'),
        ),
        migrations.AddField(
            model_name='outboundemail',
            name='source_recommendation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_outbound_emails', to='recommendations.airecommendation'),
        ),
        migrations.AddField(
            model_name='inboundemail',
            name='source_outbound',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='simulated_replies', to='emailing.outboundemail'),
        ),
    ]
