# Generated by Django 6.0.3 on 2026-03-19 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailing', '0002_remove_emailthread_linked_company_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='outboundemail',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='outboundemail',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outboundemail',
            name='failed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outboundemail',
            name='failure_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='outboundemail',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='outboundemail',
            name='to_email',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
