# Ruta: /home/sulheru/OptiGrid_Project/og_pilot/optigrid_crm/apps/emailing/migrations/0004_outboundemail_email_type.py
# Generated by Django 6.0.3 on 2026-03-19 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailing', '0003_alter_outboundemail_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='outboundemail',
            name='email_type',
            field=models.CharField(choices=[('first_contact', 'First contact'), ('followup', 'Follow-up')], default='first_contact', max_length=30),
        ),
    ]
