# Ruta: /home/sulheru/OptiGrid_Project/og_pilot/optigrid_crm/apps/emailing/migrations/0005_inboundemail.py
# Generated by Django 6.0.3 on 2026-03-19 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailing', '0004_outboundemail_email_type'),
        ('opportunities', '0004_opportunity_last_analyzed_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='InboundEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_email', models.CharField(blank=True, default='', max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewed', 'Reviewed'), ('linked', 'Linked')], default='new', max_length=20)),
                ('reply_type', models.CharField(choices=[('interested', 'Interested'), ('not_now', 'Not now'), ('not_interested', 'Not interested'), ('needs_info', 'Needs info'), ('unclear', 'Unclear')], default='unclear', max_length=30)),
                ('received_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbound_emails', to='opportunities.opportunity')),
                ('source_outbound', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='simulated_replies', to='emailing.outboundemail')),
            ],
            options={
                'ordering': ['-received_at', '-created_at'],
            },
        ),
    ]
