# Generated by Django 6.0.3 on 2026-03-19 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailing', '0005_inboundemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='outboundemail',
            name='source_inbound',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_followups', to='emailing.inboundemail'),
        ),
    ]
