# Ruta: /home/sulheru/OptiGrid_Project/og_pilot/optigrid_crm/apps/emailing/migrations/0007_inboundinterpretation_inbounddecision.py
# LLM INFO: Este encabezado contiene la ruta absoluta de origen. Mantenlo para preservar el contexto de ubicación del archivo.
# Generated by Django 6.0.3 on 2026-03-20 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailing', '0006_outboundemail_source_inbound'),
    ]

    operations = [
        migrations.CreateModel(
            name='InboundInterpretation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intent', models.CharField(choices=[('interested', 'Interested'), ('objection', 'Objection / Needs info'), ('delay', 'Delay / Not now'), ('rejection', 'Rejection'), ('unclear', 'Unclear')], default='unclear', max_length=32)),
                ('urgency', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=16)),
                ('sentiment', models.CharField(choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative')], default='neutral', max_length=16)),
                ('recommended_action', models.CharField(choices=[('advance_opportunity', 'Advance opportunity'), ('send_information', 'Send information'), ('schedule_followup', 'Schedule follow-up'), ('mark_lost', 'Mark lost'), ('send_clarification', 'Send clarification')], default='send_clarification', max_length=32)),
                ('confidence', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('rationale', models.TextField(blank=True, default='')),
                ('signals_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inbound_email', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_interpretation', to='emailing.inboundemail')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InboundDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('advance_opportunity', 'Advance opportunity'), ('send_information', 'Send information'), ('schedule_followup', 'Schedule follow-up'), ('mark_lost', 'Mark lost'), ('send_clarification', 'Send clarification')], max_length=32)),
                ('status', models.CharField(choices=[('suggested', 'Suggested'), ('applied', 'Applied'), ('dismissed', 'Dismissed')], default='suggested', max_length=16)),
                ('summary', models.CharField(blank=True, default='', max_length=255)),
                ('payload_json', models.JSONField(blank=True, default=dict)),
                ('requires_approval', models.BooleanField(default=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inbound_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_decisions', to='emailing.inboundemail')),
                ('interpretation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='emailing.inboundinterpretation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
