# Ruta: /home/sulheru/OptiGrid_Project/og_pilot/optigrid_crm/apps/lead_research/migrations/0001_initial.py
# LLM INFO: Este encabezado contiene la ruta absoluta de origen. Mantenlo para preservar el contexto de ubicación del archivo.
# Generated by Django 6.0.3 on 2026-03-19 14:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'New'), ('approved', 'Approved'), ('dismissed', 'Dismissed')], default='new', max_length=20)),
                ('company_name', models.CharField(max_length=255)),
                ('normalized_company_name', models.CharField(db_index=True, max_length=255)),
                ('website', models.URLField(blank=True, default='')),
                ('website_domain', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('country', models.CharField(blank=True, default='', max_length=100)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('industry', models.CharField(blank=True, default='', max_length=100)),
                ('employee_range', models.CharField(blank=True, default='', max_length=100)),
                ('fit_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('timing_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('novelty_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('confidence', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('source_query', models.CharField(blank=True, default='', max_length=500)),
                ('source_provider', models.CharField(blank=True, default='gemini_mock', max_length=100)),
                ('rationale_codes', models.JSONField(blank=True, default=list)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('first_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('dismissed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_suggestions', to='companies.company')),
            ],
            options={
                'ordering': ['-fit_score', '-timing_score', '-novelty_score', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal_type', models.CharField(choices=[('funding', 'Funding'), ('hiring', 'Hiring'), ('expansion', 'Expansion'), ('growth', 'Growth'), ('tech', 'Tech'), ('trigger', 'Trigger')], max_length=50)),
                ('signal_value', models.CharField(blank=True, default='', max_length=255)),
                ('confidence', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('source_provider', models.CharField(blank=True, default='gemini_mock', max_length=100)),
                ('source_ref', models.CharField(blank=True, default='', max_length=500)),
                ('observed_at', models.DateTimeField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('suggestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='lead_research.leadsuggestion')),
            ],
            options={
                'ordering': ['-confidence', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadResearchSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discovery_payload', models.JSONField(blank=True, default=dict)),
                ('enrichment_payload', models.JSONField(blank=True, default=dict)),
                ('hypothesis_payload', models.JSONField(blank=True, default=dict)),
                ('summary_codes', models.JSONField(blank=True, default=list)),
                ('model_name', models.CharField(blank=True, default='', max_length=100)),
                ('prompt_version', models.CharField(blank=True, default='v1', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('suggestion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='snapshot', to='lead_research.leadsuggestion')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddIndex(
            model_name='leadsuggestion',
            index=models.Index(fields=['status', 'created_at'], name='lead_resear_status_477f2a_idx'),
        ),
        migrations.AddIndex(
            model_name='leadsuggestion',
            index=models.Index(fields=['status', 'normalized_company_name'], name='lead_resear_status_3cfe8d_idx'),
        ),
        migrations.AddIndex(
            model_name='leadsuggestion',
            index=models.Index(fields=['status', 'website_domain'], name='lead_resear_status_435a9f_idx'),
        ),
        migrations.AddConstraint(
            model_name='leadsuggestion',
            constraint=models.UniqueConstraint(fields=('normalized_company_name', 'website_domain'), name='lead_suggestion_unique_name_domain'),
        ),
        migrations.AddIndex(
            model_name='leadsignal',
            index=models.Index(fields=['signal_type', 'created_at'], name='lead_resear_signal__4f103f_idx'),
        ),
        migrations.AddIndex(
            model_name='leadsignal',
            index=models.Index(fields=['suggestion', 'signal_type'], name='lead_resear_suggest_8aa893_idx'),
        ),
    ]
