# Generated by Django 6.0.3 on 2026-04-05 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BehaviorEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('value', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FAQEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='KnowledgeCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('faq', 'FAQ'), ('behavior', 'Behavior')], max_length=50)),
                ('candidate_type', models.CharField(choices=[('faq', 'FAQ'), ('behavior', 'Behavior')], max_length=50)),
                ('content', models.TextField()),
                ('source', models.CharField(default='system', max_length=255)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('source_signature', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('new', 'New'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='new', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='KnowledgeEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, default='')),
                ('vector', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VectorMemoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namespace', models.CharField(max_length=100)),
                ('key', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('embedding', models.JSONField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('source_model', models.CharField(blank=True, default='', max_length=100)),
                ('source_pk', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Behavior',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('knowledge.behaviorentry',),
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('knowledge.faqentry',),
        ),
    ]
