# Generated by Django 6.0.3 on 2026-03-28 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BehaviorEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, unique=True)),
                ('value', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='FAQEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='KnowledgeCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('source', models.CharField(blank=True, default='', max_length=255)),
                ('type', models.CharField(choices=[('behavior', 'Behavior'), ('faq', 'FAQ'), ('other', 'Other')], default='other', max_length=50)),
                ('candidate_type', models.CharField(choices=[('behavior', 'Behavior'), ('faq', 'FAQ'), ('other', 'Other')], default='other', max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('source_signature', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('new', 'New'), ('processed', 'Processed'), ('rejected', 'Rejected')], default='new', max_length=50)),
                ('confidence_score', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Behavior',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('knowledge.behaviorentry',),
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('knowledge.faqentry',),
        ),
        migrations.CreateModel(
            name='KnowledgeEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('embedding', models.JSONField(default=list)),
                ('candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='knowledge.knowledgecandidate')),
            ],
        ),
        migrations.CreateModel(
            name='VectorMemoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namespace', models.CharField(max_length=255)),
                ('key', models.CharField(max_length=255)),
                ('source_model', models.CharField(blank=True, default='', max_length=255)),
                ('source_pk', models.CharField(blank=True, default='', max_length=255)),
                ('content', models.TextField()),
                ('embedding', models.JSONField(default=list)),
            ],
            options={
                'unique_together': {('namespace', 'key')},
            },
        ),
    ]
