# Generated by Django 6.0.3 on 2026-03-28 09:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Behavior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('version', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('version', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='KnowledgeEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vector', models.JSONField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='behaviorentry',
            name='source_candidate',
        ),
        migrations.RemoveField(
            model_name='behaviorentry',
            name='supersedes',
        ),
        migrations.RemoveField(
            model_name='capabilityproposalentry',
            name='source_candidate',
        ),
        migrations.RemoveField(
            model_name='capabilityproposalentry',
            name='supersedes',
        ),
        migrations.RemoveField(
            model_name='faqentry',
            name='source_candidate',
        ),
        migrations.RemoveField(
            model_name='faqentry',
            name='supersedes',
        ),
        migrations.DeleteModel(
            name='VectorMemoryItem',
        ),
        migrations.AlterModelOptions(
            name='knowledgecandidate',
            options={},
        ),
        migrations.RemoveField(
            model_name='knowledgecandidate',
            name='candidate_type',
        ),
        migrations.RemoveField(
            model_name='knowledgecandidate',
            name='reviewed_at',
        ),
        migrations.RemoveField(
            model_name='knowledgecandidate',
            name='source_signature',
        ),
        migrations.AddField(
            model_name='knowledgecandidate',
            name='type',
            field=models.CharField(choices=[('faq', 'FAQ'), ('behavior', 'Behavior'), ('capability', 'Capability Proposal')], default='faq', max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='knowledgecandidate',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='knowledgecandidate',
            name='source_examples',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='knowledgeembedding',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embeddings', to='knowledge.knowledgecandidate'),
        ),
        migrations.DeleteModel(
            name='BehaviorEntry',
        ),
        migrations.DeleteModel(
            name='CapabilityProposalEntry',
        ),
        migrations.DeleteModel(
            name='FAQEntry',
        ),
    ]
