# Generated by Django 6.0.3 on 2026-03-31 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factrecord',
            name='confidence',
        ),
        migrations.RemoveField(
            model_name='factrecord',
            name='fact_value',
        ),
        migrations.RemoveField(
            model_name='factrecord',
            name='observed_at',
        ),
        migrations.AddField(
            model_name='factrecord',
            name='payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='factrecord',
            name='source_id',
            field=models.IntegerField(),
        ),
    ]
