# Generated by Django 6.0.3 on 2026-04-05 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope_type', models.CharField(max_length=50)),
                ('scope_id', models.CharField(max_length=100)),
                ('recommendation_type', models.CharField(max_length=100)),
                ('recommendation_text', models.TextField()),
                ('confidence', models.FloatField()),
                ('status', models.CharField(choices=[('new', 'New'), ('materialized', 'Materialized'), ('dismissed', 'Dismissed'), ('executed', 'Executed')], default='new', max_length=50)),
                ('source', models.CharField(choices=[('rules', 'Rules'), ('llm', 'LLM'), ('merged', 'Merged')], db_index=True, default='rules', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mailbox_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendations', to='tenancy.mailboxaccount')),
                ('operating_organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendations', to='tenancy.operatingorganization')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ExecutionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(max_length=64)),
                ('request_payload', models.JSONField(blank=True, default=dict)),
                ('result_payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('started', 'Started'), ('completed', 'Completed'), ('failed', 'Failed'), ('blocked', 'Blocked')], default='started', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recommendation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_logs', to='recommendations.airecommendation')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['recommendation', 'status'], name='reco_execlog_status_idx')],
                'constraints': [models.UniqueConstraint(fields=('recommendation', 'action_type'), name='uniq_executionlog_recommendation_action')],
            },
        ),
    ]
