# Ruta: /home/sulheru/OptiGrid_Project/og_pilot/optigrid_crm/apps/recommendations/migrations/0001_initial.py
# Generated by Django 6.0.3 on 2026-03-08 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope_type', models.CharField(max_length=50)),
                ('scope_id', models.CharField(max_length=100)),
                ('recommendation_type', models.CharField(max_length=100)),
                ('recommendation_text', models.TextField()),
                ('confidence', models.FloatField()),
                ('status', models.CharField(default='active', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
