# Generated by Django 6.0.3 on 2026-03-09 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airecommendation',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('materialized', 'Materialized'), ('dismissed', 'Dismissed'), ('executed', 'Executed')], default='new', max_length=50),
        ),
    ]
