# Generated by Django 6.0.3 on 2026-04-03 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0005_executionlog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='airecommendation',
            options={'ordering': ['-created_at', '-id']},
        ),
    ]
