# Generated by Django 6.0.3 on 2026-03-28 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('external_actions', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='externalactionintent',
            new_name='external_ac_intent__32184c_idx',
            old_name='external_ac_intent__f9bc7f_idx',
        ),
        migrations.RenameIndex(
            model_name='externalactionintent',
            new_name='external_ac_port_na_261af0_idx',
            old_name='external_ac_port_na_45ece4_idx',
        ),
        migrations.RenameIndex(
            model_name='externalactionintent',
            new_name='external_ac_provide_a20757_idx',
            old_name='external_ac_provider_56f7fc_idx',
        ),
        migrations.RenameIndex(
            model_name='externalactionintent',
            new_name='external_ac_approva_8c8499_idx',
            old_name='external_ac_approval_563470_idx',
        ),
        migrations.RenameIndex(
            model_name='externalactionintent',
            new_name='external_ac_executi_514b5b_idx',
            old_name='external_ac_executi_5046f5_idx',
        ),
        migrations.RenameIndex(
            model_name='externalactionintent',
            new_name='external_ac_dispatc_0c14d6_idx',
            old_name='external_ac_dispatch_4bfbc3_idx',
        ),
    ]
