# Generated by Django 6.0.3 on 2026-04-05 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('external_actions', '0001_initial'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalactionintent',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='external_action_intents', to='tasks.crmtask'),
        ),
        migrations.AddIndex(
            model_name='externalactionintent',
            index=models.Index(fields=['intent_type'], name='external_ac_intent__32184c_idx'),
        ),
        migrations.AddIndex(
            model_name='externalactionintent',
            index=models.Index(fields=['port_name'], name='external_ac_port_na_261af0_idx'),
        ),
        migrations.AddIndex(
            model_name='externalactionintent',
            index=models.Index(fields=['provider'], name='external_ac_provide_a20757_idx'),
        ),
        migrations.AddIndex(
            model_name='externalactionintent',
            index=models.Index(fields=['approval_status'], name='external_ac_approva_8c8499_idx'),
        ),
        migrations.AddIndex(
            model_name='externalactionintent',
            index=models.Index(fields=['execution_status'], name='external_ac_executi_514b5b_idx'),
        ),
        migrations.AddIndex(
            model_name='externalactionintent',
            index=models.Index(fields=['dispatch_status'], name='external_ac_dispatc_0c14d6_idx'),
        ),
    ]
