# Ruta: /home/sulheru/OptiGrid_Project/og_pilot/optigrid_crm/config/settings.py
# LLM INFO: Este encabezado contiene la ruta absoluta de origen. Mantenlo para preservar el contexto de ubicación del archivo.
"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = "django-insecure--71jk9bybha5rpx^98)b*+&8rsf&a1elp1qnj8kb3-eq@r86)t"
DEBUG = True
ALLOWED_HOSTS = []

INSTALLED_APPS = [
    "apps.core",
    "apps.lead_research",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "apps.companies",
    "apps.contacts",
    "apps.emailing",
    "apps.facts",
    "apps.inferences",
    "apps.updates",
    "apps.recommendations",
    "apps.tasks",
    "apps.opportunities",
    "apps.events",
    'apps.strategy',
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True

STATIC_URL = "/static/"

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

CELERY_BROKER_URL = "redis://localhost:6379/0"
CELERY_RESULT_BACKEND = "redis://localhost:6379/0"

OPPORTUNITY_ANALYSIS_ENABLED = True
OPPORTUNITY_ANALYSIS_SCHEDULE_MINUTES = 60
OPPORTUNITY_ANALYSIS_MIN_RECHECK_HOURS = 12
OPPORTUNITY_ANALYSIS_BATCH_SIZE = 50
OPPORTUNITY_ANALYSIS_VERSION = "v2"

AUTO_TASKING_ENABLED = True
AUTO_TASKING_MIN_PRIORITY = "medium"
AUTO_TASKING_ALLOWED_ACTIONS = [
    "schedule_followup",
    "advance_opportunity",
    "review_pricing_strategy",
    "review_opportunity_stall",
    "define_next_action",
]

LEAD_RESEARCH_USE_MOCK = True

LEAD_RESEARCH_DISCOVERY_QUERIES = [
    "DACH mid-market companies with infrastructure growth signals",
    "Companies hiring network cloud security infrastructure in Germany Austria Switzerland",
    "Recent expansion or funding signals in industrial and B2B software companies in DACH",
]

CELERY_BEAT_SCHEDULE = globals().get("CELERY_BEAT_SCHEDULE", {})
CELERY_BEAT_SCHEDULE["lead-signal-discovery-every-6-hours"] = {
    "task": "apps.lead_research.tasks.run_lead_signal_discovery",
    "schedule": 60 * 60 * 6,
}

INBOX_AUTO_APPLY_ENABLED = True
INBOX_AUTO_APPLY_SCORE_THRESHOLD = 60

INBOX_AUTO_BLOCKED_ACTIONS = [
    "mark_lost",
    "advance_opportunity",
]

INBOX_AUTO_BLOCK_ON_RISK_FLAGS = [
    "low_confidence",
    "unclear_intent",
    "negative_sentiment",
    "contradictory_signals",
    "requires_approval",
    "blocked_action",
    "sensitive_stage_change",
]
